---
services:
  coordinator:
    image: labgrid/coordinator:latest
    platform: linux/amd64
    hostname: coordinator
    restart: always
    volumes:
    - ./conf/coordinator:/opt/crossbar
    network_mode: host
  exporter:
    image: labgrid/exporter:latest
    platform: linux/amd64
    network_mode: host
    restart: always
    privileged: true
    volumes:
    - ./conf/exporter/exporter.yaml:/opt/conf/exporter.yaml
    - /dev:/dev
    - /run/udev:/run/udev
    command: "/entrypoint.sh -x ws://${HOSTNAME}:20408/ws -i"
    deploy:
      resources:
        limits:
          memory: 1G
